ozon/urls.py
from django.urls import path
from . import views

app_name = 'ozon'

urlpatterns = [
    path('', views.XlFormCreateView.as_view(), name='form'),
    path("<int:pk>/", views.XlFormDetailView.as_view(), name="detail"),
    path("edit/<int:pk>/", views.XlFormUpdateView.as_view(), name="edit"),
    path('list/', views.XlFormListView.as_view(), name='list'),
    path('edit_xl/<int:pk>/', views.edit_xl, name='edit_xl'),
    path('formatter/', views.Formatter.as_view(), name='formatter'),
    path('test/', views.FormView.as_view(), name='test')

]

purchaseorder/urls.py
from django.urls import path
from . import views

app_name = 'purchaseorder'

urlpatterns = [
    path('', views.OrderList.as_view(), name='main'),
    path('order/<slug:slug>/', views.OrderPositions.as_view(), name='order'),
    path(
        'create_doc/<slug:slug>/',
        views.CreateOrderDoc.as_view(),
        name='create_doc',
    ),
    path(
        'document/<slug:slug>/',
        views.UpdateOrderDoc.as_view(),
        name='document'
    ),
    path('documents/', views.DocListViews.as_view(), name='doc_list'),
    path(
        'document/<int:pk>/delete/',
        views.DocDeleteView.as_view(),
        name='doc_delete'
    ),
    path(
        'product/<int:pk>/update/<slug:slug>/',
        views.DocUpdateProductFactView.as_view(),
        name='product_update_fact'
    ),
    path('document/<slug:slug>/products_update',
         views.DocUpdateProducts.as_view(), name='update_products'),
    path('product/detail/<slug:slug>/',
         views.ProductDetail.as_view(), name='product_detail'),
    path('product/detail/<slug:slug>/update',
         views.ProductUpdateView.as_view(), name='product_detail_update'),
    path('download-label/', views.download_label, name='download_label'),
    path('create_xcel/<slug:slug>/',
         views.CreateDownloadXcelDoc.as_view(), name='download_doc'),
    path('product/detail/<int:pk>/label_form/',
         views.ProductCreateLabelForm.as_view(), name='get_label_form'),
]

sklad_tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('ozon/', include('ozon.urls')),
    path('purchaseorder/', include('purchaseorder.urls')),
    path("select2/", include("django_select2.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchaseorder/models.py
from django.db import models


class Order(models.Model):
    name = models.CharField(max_length=100, verbose_name='Номер заказа')
    slug = models.SlugField(max_length=100, verbose_name='Слагифицирован')
    order_id = models.CharField(
        max_length=100, verbose_name='Api ID заказа', unique=True
    )
    created_at = models.DateField('Дата создания', auto_now_add=True)
    xl_doc = models.FileField(
        'Итоговый документ', blank=True, null=True, upload_to='purchaseorder'
    )


class Product(models.Model):
    product_id = models.SlugField(
        max_length=100, verbose_name='ID товара', unique=True
    )
    name = models.CharField(max_length=250, verbose_name='Наименование')
    code = models.CharField(
        max_length=100, verbose_name='Код товара', null=True, blank=True
    )
    article = models.CharField(
        max_length=100, verbose_name='Код товара', null=True, blank=True
    )
    barcodes = models.CharField(
        max_length=250, blank=True, null=True, verbose_name='Штрих-коды'
    )
    cell_number = models.CharField(
        verbose_name='Номер ячейки', max_length=100, null=True, blank=True
    )
    image = models.ImageField(
        verbose_name='Фото', blank=True, upload_to='purchaseorder', null=True)

    miniature = models.ImageField(
        verbose_name='фото миниатюра', blank=True, upload_to='purchaseorder',
        null=True
    )
    description = models.TextField('Описание', blank=True, null=True)


class PurchaseOrder(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name='products')
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='products'
    )
    quantity = models.IntegerField('Заказано шт')
    summ = models.FloatField('Сумма')
    fact = models.IntegerField('Фактическое количество', default=0)
    plus = models.IntegerField('Посчитано', null=True, blank=True)
    comment = models.CharField(
        'Комментарий', max_length=250, null=True, blank=True)

purchaseorder/forms.py
from django.forms import ModelForm
from django import forms
from django.core.exceptions import ValidationError
from .models import PurchaseOrder, Product


class ProductForm(ModelForm):
    plus = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control'}))
    comment = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=250
    )

    class Meta:
        model = PurchaseOrder
        fields = ('plus', 'comment')


class FactForm(ModelForm):
    class Meta:
        model = PurchaseOrder
        fields = ('fact', 'comment')

    def clean_fact(self):
        data = self.cleaned_data['fact']
        if data < 0:
            raise ValidationError('Чисто не может быть отрицательным')
        return data


class DetailLabelForm(ModelForm):
    date = forms.DateField(
        label='Дата приемки',
        widget=forms.DateInput(attrs={'type': 'date'}))
    big = forms.BooleanField(label='Большая', required=False)

    class Meta:
        model = Product
        fields = ('name', 'code', 'barcodes', 'cell_number')

purchaseorder/views.py
import os
from dotenv import load_dotenv
import requests
from django.shortcuts import redirect, get_object_or_404, render
from django.conf import settings
from django.urls import reverse_lazy
from django.http import HttpResponse, Http404
from django_ratelimit.decorators import ratelimit
from django.utils.decorators import method_decorator
from django.views import generic, View
from django.db import transaction
from django.forms import modelformset_factory
from pytils.translit import slugify

from .models import PurchaseOrder, Order, Product
from .forms import ProductForm, FactForm, DetailLabelForm
from utils.purchaseorder.label_generator import (
    create_label, create_user_label, create_big_label)
from utils.purchaseorder.create_doc import create_report

load_dotenv()

TOKEN = os.getenv('ms_token')
if not TOKEN:
    raise ValueError('Требуется токен Моего скалада.')

HEADERS = {
    'Authorization': f'Bearer {TOKEN}',
    'Content-type': 'application/json'
}

PARAMS = (('limit', 50),)


class ResponseMixin:
    @staticmethod
    def response(url, headers=HEADERS, params=PARAMS):
        return requests.get(
            url=url,
            headers=headers,
            params=params
        )


class DetailUpdateMixin(ResponseMixin):
    url = 'https://api.moysklad.ru/api/remap/1.2/entity/product/'

    def get_postition(self, pk):
        response = self.response(self.url + pk + '/?expand=images')
        if response.status_code != 200:
            return
        return response

    def get_valid_info(self, response):
        miniature = 'purchaseorder/preview.jpg'
        image = 'purchaseorder/previewBIG.jpg'
        resp = response.json()
        pk = resp.get('id')
        name = resp.get('name')
        if not pk or not name:
            return
        code = resp.get('code')
        article = resp.get('article')
        barcodes = resp.get('barcodes')
        attributes = resp.get('attributes')
        description = resp.get('description')
        cell = ListCreatePositionsDocMixin.get_cell(attributes)
        miniature_resp = resp.get('images').get('rows')
        if miniature_resp:
            miniature_url = miniature_resp[0]['miniature']['downloadHref']
            miniature = ListCreatePositionsDocMixin.download_image(
                pk, miniature_url
            )
            image = self.download_big_size_photo(resp)
        return (
            pk, name, code, article, barcodes, cell, miniature, image,
            description,
        )

    def download_big_size_photo(self, response):
        try:
            pk = response['id']
            images = response['images']['rows']
            images_download_url = images[0]['meta']['downloadHref']
        except LookupError:
            return
        image = ListCreatePositionsDocMixin.download_image(
            pk, images_download_url, 'BIG'
        )
        return image


class ListCreatePositionsDocMixin:

    def get_positions(self):
        pk = self.kwargs['slug']
        url = (
            f'https://api.moysklad.ru/api/remap/1.2/entity/purchaseorder/{pk}'
        )
        self.number = self.response(url).json()
        url += '/positions?expand=assortment.images'
        dict_response = self.response(url, params=None).json()
        response = dict_response.get('rows')
        errors = dict_response.get('errors')
        if errors:
            error = errors[0].get('error')
            raise Http404(f'Ответ моего склада вернул: {error}')
        self.positions_quantity = len(response)
        self.positions = response

    @staticmethod
    def get_cell(cell_attr):
        cell_id = '17bbadc0-786b-11ec-0a80-06bd004b0ee2'
        cell_value = ''
        if cell_attr:
            for cell in cell_attr:
                if cell['id'] == cell_id:
                    cell_value = cell['value']

        return cell_value

    def get_valid_data(self, info):
        if not (product_id := info['assortment'].get('id')):
            raise ValueError('ID товара не получено от Моего склада.')
        name = info['assortment'].get('name')
        barcodes = None
        if barcodes := info['assortment'].get('barcodes'):
            barcodes = str(barcodes)
        code = info['assortment'].get('code')
        article = info['assortment'].get('article')
        cell_attr = info['assortment'].get('attributes')
        cell_number = self.get_cell(cell_attr)
        description = info['assortment'].get('description')
        return (
            product_id, name, barcodes, code, article, cell_number,
            description
        )

    def get_image(self, info):
        product_id = info['assortment'].get('id')
        miniature_url = info['assortment']['images'].get('rows')
        image_miniature = 'purchaseorder/preview.jpg'
        if miniature_url:
            miniature_url = (
                miniature_url[0].get('miniature').get('downloadHref'))
            image_miniature = (
                self.download_image(product_id, miniature_url)
                or image_miniature)
        return image_miniature

    @staticmethod
    def download_image(product_id, image_url, prefix=''):
        response = requests.get(image_url, headers=HEADERS, stream=True)
        if response.status_code != 200:
            return

        content_type = response.headers.get('Content-Type')
        if content_type:
            extension = '.' + content_type.split('/')[1]
        else:
            return

        file_path = os.path.join(
            settings.MEDIA_ROOT,
            'purchaseorder', product_id + prefix + extension)
        media_path = 'purchaseorder/' + product_id + prefix + extension

        with open(file_path, 'wb') as file:
            for chunk in response.iter_content(chunk_size=1024):
                if chunk:
                    file.write(chunk)

        return media_path


class OrderList(ResponseMixin, generic.TemplateView):
    template_name = 'purchaseorder/main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.get_order_list()
        context["order_list"] = self.order_list
        return context

    def get_order_list(self):
        url = ('https://api.moysklad.ru/api/remap/1.2/entity/purchaseorder'
               '?order=created,desc&expand=agent')
        dict_response = self.response(url).json()
        response = dict_response.get('rows')
        if not response:
            error = dict_response.get('errors')[0].get('error')
            raise Http404(f'Ответ моего склада вернул: {error}')
        self.order_list = response


class OrderPositions(
    ResponseMixin,
    ListCreatePositionsDocMixin,
    generic.TemplateView
):
    template_name = 'purchaseorder/order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.get_positions()
        context["context"] = self.positions
        context['number'] = self.number
        context['positions_quantity'] = self.positions_quantity
        context["back_page"] = self.request.META.get('HTTP_REFERER')
        return context


class CreateOrderDoc(
    ResponseMixin,
    ListCreatePositionsDocMixin,
    View
):
    @method_decorator(ratelimit(key='ip', rate='1/1m', method='POST'))
    def post(self, request, *args, **kwargs):

        try:
            order_object = Order.objects.get(order_id=self.kwargs['slug'])
            return redirect('purchaseorder:document', order_object.slug)

        except Order.DoesNotExist:
            self.get_positions()
            object_to_create = []
            order_name = slugify(self.number['name'])
            order = Order.objects.create(
                name=self.number['name'], slug=order_name,
                order_id=self.number['id'])

        for info in self.positions:
            (product_id, name, barcodes,
             code, article, cell_number,
             description) = self.get_valid_data(info)
            try:
                product = Product.objects.get(
                    product_id=product_id
                )
                if (product.name != name
                        or product.barcodes != barcodes
                        or product.code != code
                        or product.article != article
                        or product.cell_number != cell_number
                        or product.description != description):
                    product.name = name
                    product.barcodes = barcodes
                    product.code = code
                    product.article = article
                    product.cell_number = cell_number
                    product.description = description
                    product.save()
            except Product.DoesNotExist:
                miniature = self.get_image(info)
                product = Product.objects.create(
                        product_id=product_id,
                        name=name,
                        barcodes=barcodes,
                        code=code,
                        article=article,
                        cell_number=cell_number,
                        miniature=miniature,
                        description=description,
                )
            new_obj = PurchaseOrder(
                order=order,
                quantity=info['quantity'],
                summ=info['price'],
                fact=0,
                product=product
            )

            object_to_create.append(new_obj)
        with transaction.atomic():
            PurchaseOrder.objects.bulk_create(object_to_create)

        return redirect('purchaseorder:document', order_name)


class UpdateOrderDoc(View):
    """Работа с документом."""
    template_name = 'purchaseorder/create_doc.html'

    def get(self, request, slug):
        order, formset = self.get_data(request, slug)
        context = self.get_context(formset, order)
        return render(request, self.template_name, context=context)

templates/purchaseorder/create_doc.html
{% extends "base.html" %}
{% block title %}
  Работа с документом {{number}}
{% endblock %}
{% block content %}
<form method="POST" action="{% url 'purchaseorder:update_products' order.order_id %}">
  <div class="d-flex justify-content-between">
    {% csrf_token %}
    <button type="submit" class="btn btn-dark btn">Обновить документ</button>
    <a class="btn btn-dark btn" href="{% url 'purchaseorder:download_doc' order.order_id %}">Сформировать файл</a>
  </div>
</form>
  <div class="d-flex justify-content-between">
    <div>
      <h1>Документ заказа: {{order.name}} </h1>
      <h3>Позиций в заказе: {{ len_doc }} </h3>
    </div>
    <div>
      <br><br>
    <a class="btn btn-primary btn" href="{% url 'purchaseorder:download_label' %}"  download>Скачать этикетку</a>
    </div>
  </div>
  <form method="post">
    {% csrf_token %}
    <table class="table table-sm table-striped">
      <thead>
        <br>
        <tr class="table-secondary">
          <th scope="col">№</th>
          <th scope="col">Фото</th>
          <th scope="col">Название</th>
          <th scope="col">Код</th>
          <th scope="col">Баркод</th>
          <th scope="col">Заказ</th>
          <th scope="col">Факт</th>
          <th scope="col">Плюс</th>
          <th scope="col">Комментарий</th>
          <th scope="col">корректировать</th>
        </tr>
      </thead>
      <tbody>
        {% for form in product_formset %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td class="text-center">
            <img src="{{ MEDIA_URL }}{{ form.instance.product.miniature }}" width="85" height="85">
          </td>
          <td><a class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'purchaseorder:product_detail' form.instance.product.product_id %}">
            {{ form.instance.product.name }}</a></td>
          <td>{{ form.instance.product.code }}</td>
          <td>{% if form.instance.product.barcodes %}
            {{ form.instance.product.barcodes }}{% else %}{% endif %}</td>
          <td>{{ form.instance.quantity|floatformat:0 }}</td>
          {{ form.management_form }}
          <td>{{ form.instance.fact }}</td>
          <td>{{ form.plus }}</td>
          <td>{{ form.comment }}</td>
          <td><a class="btn btn-dark btn-sm" href="{% url 'purchaseorder:product_update_fact' form.instance.id order.slug %}">Изменить факт</td></a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <button type="submit" class="btn btn-dark">Сохранить</button>
  </form>
{% endblock %}

templates/purchaseorder/create_download_xcel.html
{% extends "base.html" %} 
{% block title %} 
        Скачать результат приемки {{object.name}}
{% endblock %} 
{% block content %}
<a href="{{ back_page }}" class="btn btn-primary" role="button" style="width: 150px">Назад</a>
<br><br>
<div class="row justify-content-center">  <!--  Создаем строку, выравниваем ее по центру -->
  <div class="col-md-10">  <!--  Карточка в 6 колонках -->
    <div class="card mb-3 card text-white bg-dark mb-3">
      <div class="card-header text-white bg-dark mb-3 text-center">
        Результат приемки {{object.name}}
      </div>
        <div class="card-body ">
          <div class="card-header mb-3">
            Документ: {{order.name}}
          </div>
          <div class="card-header mb-3">
            Создано: {{order.created_at}}
          </div>
          <div class="card-header mb-3">
            Товаров в заказе: {{ count_product }}
          </div>
          <a class="btn btn-primary" href="{{MEDIA_URL}}{{order.xl_doc}}"  download>Скачать файл</a>
        </div>
    </div>
  </div>
</div> 

{%include "includes/paginator.html" %}
{% endblock %}

templates/purchaseorder/main.html
{% extends "base.html" %}
{% block title %}
  Список заказов из моего склада
{% endblock %}
{% block content %}
  <a class="btn btn-dark btn" href="{% url 'purchaseorder:doc_list' %}">Список созданых документов</a>
  <br><br>
  <div class="card text-center">
    <div class="card-header"><h5>Заказы в "Моем складе"</h5></div> <div class="card-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Название</th>
            <th scope="col">Агент</th>
            <th scope="col">Сумма Руб</th>
            <th scope="col">Дата создания</th>
            <th scope="col">Просмотр</th>
          </tr>
        </thead>
        <tbody>
          {% for i in order_list %}
          <tr>
            <td>{{ i.name }}</td>
            <td>{{ i.agent.name }}</td>
            <td>{{ i.sum|floatformat:2 }}</td>
            <td>{{ i.created }}</td>
            <td><a class="btn btn-dark btn-sm" href="{% url 'purchaseorder:order' i.id %}">Открыть</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

templates/purchaseorder/order.html
{% extends "base.html" %}
{% block title %}
  Просмотр документа {{number.name}}
{% endblock %}
{% block content %}
  <form method="POST" action="{% url 'purchaseorder:create_doc' number.id %}">
    <div class="d-flex justify-content-between">
    <a href="{{ back_page }}" class="btn btn-primary" role="button" style="width: 150px">Назад</a>
    {% csrf_token %}
    <input type="hidden" id="api_data" name="api_data">
    <button type="submit" class="btn btn-dark">Создать документ</button>
    </div>
</form>
<h4>Позиций в заказе: {{ positions_quantity }}</h4>
  <div class="card text-center">
    <div class="card-header"><h5>
      Позиции в заказe № {{number.name}}
      </h5>
    </div>
  <div class="card-body">
  <table class="table table-sm table-striped">
    <thead>
      <tr>
        <th scope="col">№</th>
        <th scope="col">Название</th>
        <th scope="col">Код</th>
        <th scope="col">Баркод</th>
        <th scope="col">Сумма</th>
        <th scope="col">Заказано</th>
      </tr>
    </thead>
    <tbody>
      {% for i in context %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ i.assortment.name }}</td>
        <td>{{ i.assortment.code }}</td>
        <td>{{ i.assortment.barcodes }}</td>
        <td>{{ i.price }}</td>
        <td>{{ i.quantity|floatformat:0 }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
{% endblock %}

templates/purchaseorder/order_confirm_delete.html
{% extends "base.html" %} 
{% block title %} 
        Удаление документа приемки {{object.name}}
{% endblock %} 
{% block content %}


<div class="row justify-content-center">  <!--  Создаем строку, выравниваем ее по центру -->
  <div class="col-md-10">  <!--  Карточка в 6 колонках -->
    <div class="card mb-3 card text-white bg-dark mb-3">
      <div class="card-header text-white bg-dark mb-3 text-center">
        Удаление документа приемки {{object.name}}
      </div>
        <div class="card-body ">
          <div class="card-header mb-3">
            Документ: {{object.name}}
          </div>
          <div class="card-header mb-3">
            Slug: {{object.slug}}
          </div>
          <div class="card-header mb-3">
            Создано: {{object.created_at}}
          </div>
        <form method="post">
            {% csrf_token %}
            <p>Вы уверены, что хотите удалить документ приемки"{{ object.name }}"?</p>
            <button type="submit" class="btn btn-danger btn-sm">Удалить</button>
            <a class="btn btn-success btn-sm" href="{% url 'purchaseorder:doc_list' %}">Не удалять</a>
           </form>
           
        </div>
    </div>
  </div>
</div> 

{%include "includes/paginator.html" %}
{% endblock %}

templates/purchaseorder/order_list.html
{% extends "base.html" %}
{% block title %}
        Список созданных документов
{% endblock %}
{% block content %}
<div class="mb-3">
<a class="btn btn-dark btn" href="{% url 'purchaseorder:main' %}">Список заказов поставщику "Мой Склад"</a>
</div>
<h5> Созданные документы</h5>
<div class="row justify-content-center">
  <div class="col-md-12">
      {% if page_obj %}
        <div class="row">  <!--  Добавляем row для размещения карточек в ряд -->
          {% for order in page_obj %}
          <div class="col-md-4 mb-3">  <!--  Добавляем col для разделения карточек -->
            <div class="card mb-3 text-white bg-dark">  <!--  Новая карточка для каждого заказа -->
              <div class="card-header">
                <h5 class="card-title">Заказ: {{order.name}}</h5>  <!--  Заголовок карточки -->
              </div>
              <div class="card-body">
                <p class="card-text">Slug: {{order.slug}}</p>
                <p class="card-text">Создано: {{order.created_at}}</p>
                  <div class="d-flex justify-content-between">
                  <a class="btn btn-light btn-sm" href="{% url 'purchaseorder:document' order.slug %}">Открыть документ</a>
                  <a class="btn btn-danger btn-sm" href="{% url 'purchaseorder:doc_delete' order.id %}"> <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                    <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
                  </svg></a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
      {% else %}
        <div class="card-body text-center">
          <p>Нет заказов</p>
        </div>
      {% endif %}
    </div>
  </div>
</div> 

{%include "includes/paginator.html" %}
{% endblock %}

templates/purchaseorder/product_detail.html
{% extends "base.html" %}
{% block title%}
Товар №{{ object.id }}
{% endblock title %}
{% block content %}
<form method="POST" action="{% url 'purchaseorder:product_detail_update' object.product_id %}">
  {% csrf_token %}
  
  <div class="d-flex justify-content-between align-items-center">
    <a href="{{ back_page }}" class="btn btn-primary" role="button" style="width: 150px">Назад</a>

    <div class="btn-group">
      <a href="{% url 'purchaseorder:get_label_form' object.id %}" class="btn btn-primary" role="button" style="width: 150px">Этикетка</a>
      <button type="submit" class="btn btn-dark">Обновить товар</button>
    </div>
  </div>
</form>
<div class="row justify-content-center">
  <div class="col-md-10">
    <div class="card mb-3 card text-white bg-dark mb-3">
      <div class="card-header text-white bg-dark mb-3 text-center">
        ID товара: {{ object.id }}
      </div>
      <div class="card-body text-white bg-dark mb-3 d-flex flex-column">
        <img src="{{ MEDIA_URL }}{{ object.image }}" class="card-img-top"> 
        <hr>
        <h5>
          Наименование:<br> 
          {{ object.name }}
          <hr>
          Описание:<br>
          {{ object.description|linebreaks }}
          <hr>
          Штрих-коды: <br> {{ object.barcodes }}
          <hr>
          Код:<br>
          {{ object.code }}
          <hr>
          Артикул:<br> {{ object.article }} <br>
          <hr>
          Номер ячейки:<br>
          {{ object.cell_number }}
        </h5>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/purchaseorder/product_detail_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title%}
Сформировать этикетку
{% endblock title %}
{% block content %}
  <div class="d-flex justify-content-between">
    <a href="{{ back_page }}" class="btn btn-primary" role="button" style="width: 150px">Назад</a>
  </div>
  <div class="row justify-content-center"> 
    <div class="col-md-8">
      <div class="card text-white bg-dark mb-3 text-center">
        <div class="card-header">
          Сформировать этикетку
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
          <div class="btn-group-vertical w-100"> 
            {% bootstrap_button button_type="submit" content="Получить этикетку" %}
          </div>
        </form>
      </div>
    </div>
{% endblock content %}

templates/purchaseorder/purchaseorder_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Редактирование Факта
{% endblock %}

{% block content %}
<br><br>

<div class="row justify-content-center"> 
  <div class="col-md-8">
    <div class="card text-white bg-dark mb-3 text-center">
      <div class="card-header">
        Редактирование
      </div>
      <div class="card-body">
        <form method='post' enctype="multipart/form-data" id='form1'>
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="btn-group-vertical w-100"> 
          {% bootstrap_button button_type="submit" content="Отправить" %}
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}