ozon/urls.py
from django.urls import path
from . import views

app_name = 'ozon'

urlpatterns = [
    path('', views.XlFormCreateView.as_view(), name='form'),
    path("<int:pk>/", views.XlFormDetailView.as_view(), name="detail"),
    path("edit/<int:pk>/", views.XlFormUpdateView.as_view(), name="edit"),
    path('list/', views.XlFormListView.as_view(), name='list'),
    path('edit_xl/<int:pk>/', views.edit_xl, name='edit_xl'),
    path('formatter/', views.Formatter.as_view(), name='formatter'),
    path('test/', views.FormView.as_view(), name='test')

]

sklad_tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('ozon/', include('ozon.urls')),
    path('purchaseorder/', include('purchaseorder.urls')),
    path("select2/", include("django_select2.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ozon/models.py
from django.db import models
from django.urls import reverse

from sklad_tools import settings

annotacion_text = (
    """Совместимость с брендом: 
Материал: 
Цвет: """
)


class Ozon(models.Model):
    title = models.CharField(
        'Наименование', max_length=settings.DEFAULT_CHAR_LENGTH)
    article = models.CharField(
        'Артикул', max_length=settings.DEFAULT_CHAR_LENGTH,
        null=True, blank=True,
    )
    barcode = models.CharField(
        'Штрих-код', max_length=settings.DEFAULT_CHAR_LENGTH,
        null=True, blank=True
    )
    price = models.IntegerField('Цена руб.', default=10000)
    length = models.IntegerField('Длина упаковки мм.', default=180)
    width = models.IntegerField('Ширина упаковки мм.', default=120)
    height = models.IntegerField('Высота упаковки мм.', default=100)
    weight = models.IntegerField('вес', default=200)
    annotacion = models.TextField(
        'Аннотация', max_length=5000, default=annotacion_text)
    model_list = models.TextField(
        'Список совместимых устройств', max_length=5000
    )
    xcel_shablon = models.FileField('XL шаблон', upload_to='ozon_shablons')
    image = models.FileField(
        "Фото", upload_to='foto', null=True, blank=True
    )

    def get_absolute_url(self):
        return reverse("ozon:edit_xl", kwargs={"pk": self.pk})

ozon/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .utils import ParserTree

from .models import Ozon


class OzonForm(forms.ModelForm):
    class Meta:
        model = Ozon
        fields = '__all__'
        widgets = {
            'annotacion': forms.Textarea({'cols': '22', 'rows': '5'}),
            'model_list': forms.Textarea({'cols': '22', 'rows': '5'}),
            'image': forms.ClearableFileInput(attrs={'accept': 'image/*'}),
            'xcel_shablon': forms.ClearableFileInput(
                attrs={'accept': '.xlsx'}),
        }

    def clean_xcel_shablon(self):
        file = self.cleaned_data['xcel_shablon']
        if '.xlsx' not in file.name:
            raise ValidationError('Ожидается файл формата xlsx')
        return file

    def clean_image(self):
        image_formats = [
            'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp'
        ]
        file = self.cleaned_data.get('image')
        if file:
            if file.name.split('.')[-1] not in image_formats:
                raise ValidationError('Ожидается изображение.')
            return file


class FormatingForm(forms.Form):
    brand = forms.CharField(label='Брэнд', required=False)
    sep = forms.CharField(label='Разделитель', required=False)
    text = forms.CharField(label='Текст', widget=forms.Textarea(
        {'cols': '22', 'rows': '5'}), required=False,
        help_text='Будет помещено в основную таблицу при отправке данных.'
    )


class SearchForm(forms.Form):
    cat_search = forms.CharField(required=False)

ozon/views.py
from django.views.generic import CreateView, DetailView, UpdateView, ListView
from django.shortcuts import redirect, render
from django.conf import settings
from django.views import View

from .forms import OzonForm, FormatingForm
from .models import Ozon
from utils.ozon.barcode_gen import barcode_gen, barcode_set
from utils.ozon.writer_ozon_form import (
    on_confirm, excel_edit, choice_file_xl, clean_shablon_dir
)
from utils.ozon import format_string as formating
from utils.api.api import get_product

SET_BARCODS = barcode_set


class XlFormCreateView(CreateView):
    model = Ozon
    form_class = OzonForm
    text = None

    def form_valid(self, form):
        if form.instance.barcode is None:
            barcode = barcode_gen(SET_BARCODS)
            form.instance.barcode = barcode
        if form.instance.article is None:
            form.instance.article = barcode
        if form.instance.model_list is None and self.text:
            form.instance.model_list = self.text
        clean_shablon_dir(form.instance.xcel_shablon)
        return super().form_valid(form)


class XlFormDetailView(DetailView):
    model = Ozon

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["MEDIA_URL"] = settings.MEDIA_URL
        return context


class XlFormUpdateView(UpdateView):
    model = Ozon
    form_class = OzonForm
    text = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.GET:
            if 'model_list_zipcom' in self.request.GET:
                self.text = formating.model_list_zipcom(
                    self.request.GET['text']
                )
        formater = FormatingForm(initial={'text': self.text})
        context["form_formatter"] = formater
        return context

    def form_valid(self, form):
        clean_shablon_dir(form.instance.xcel_shablon)
        return super().form_valid(form)


class XlFormListView(ListView):
    model = Ozon
    ordering = '-id'
    paginate_by = 20


class Formatter(View):
    template_name = 'ozon/formatter.html'
    text = None

    def get(self, request):
        self.brand, self.sep = formating.get_Separation()
        form = FormatingForm(
            initial={'text': self.text, 'brand': self.brand, 'sep': self.sep})
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request):
        self.text = formating.get_format_strgin(
            number=self.request.POST['button'],
            text=self.request.POST['text'],
            brand=self.request.POST['brand'],
            sep=self.request.POST['sep']
        )
        self.brand, self.sep = formating.get_Separation()
        form = FormatingForm(
            initial={
                'text': self.text,
                'brand': self.brand,
                'sep': self.sep}
        )
        context = {'form': form}
        return render(request, self.template_name, context)


def edit_xl(request, pk):
    info = Ozon.objects.get(id=pk)
    on_confirm(
        info.title,
        info.article,
        info.barcode,
        info.annotacion,
        info.model_list,
        info.price,
        info.length,
        info.width,
        info.height,
        info.weight,
    )

    get_product(
        info.article,
        info.title,
        info.barcode,
        info.image,
    )
    excel_edit(choice_file_xl(info.xcel_shablon))
    return redirect('ozon:detail', pk=info.id)

templates/ozon/formatter.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
Форматирование строки Sk_tools
{% endblock %}
{% block content %}
<div class="row justify-content-center"> 
<div class="col-md-8">
  <div class="card text-white bg-dark mb-3 text-center">
    <div class="card-header">
      Форматирование списка моделей
    </div>
    <div class="card-body">
      <form method='post' id="form2">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="btn-group-vertical w-100"> 
          {% bootstrap_button button_type="submit" content="Вставить по разделителю" name="button" value="1" %}
          {% bootstrap_button button_type="submit" content="Zipcom" name="button" value="2" %}
          {% bootstrap_button button_type="submit" content="Удаление лишних переносов" name="button" value="3" %}
          {% bootstrap_button button_type="submit" content="Удалить брэнды" name="button" value="4" %}
          {% bootstrap_button button_type="submit" content="Доктор Кофемашин" name="button" value="5" %}
          {% bootstrap_button button_type="submit" content="Fiuo" name="button" value="6" %}
        </div>
      </form>
    </div>
  </div>
</div>
</div>
{% endblock %}

templates/ozon/ozon_detail.html
{% extends "base.html" %}
{% block title%}
Шаблон №{{ object.id }}
{% endblock title %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-10">
    <div class="card mb-3 card text-white bg-dark mb-3">
  <div class="card-header text-white bg-dark mb-3 text-center">
    ID записи: {{ object.id }}
  </div>
  <div class="card-body text-white bg-dark mb-3">
    Штрих-код: <br> {{ object.barcode }}
    <hr>
    Наименование:<br> {{ object.title }} <hr>
    Аннотация:<br> {{ object.annotacion }} <br>
    <hr>
    Список моделей:<br>
    {{ object.model_list }}
  </div>
</div>
</div>
</div>

    <a class="btn btn-success btn-sm" href="{{MEDIA_URL}}{{object.xcel_shablon}}"  download>Скачать шаблон</a>
    <a class="btn btn-dark btn-sm" href="{% url 'ozon:edit' object.id %}">Редактировать</a>
{% endblock content %}

templates/ozon/ozon_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Работа с шаблонами OZON
{% endblock %}

{% block content %}
<a class="btn btn text-muted" href="{% url 'ozon:list' %}">Список обработанных шаблонов</a> 
<a class="btn btn text-muted" href="{% url 'ozon:formatter' %}">Форматирование текста</a> 

<br><br>

<div class="row justify-content-center"> 
  <div class="col-md-8">
    <div class="card text-white bg-dark mb-3 text-center">
      <div class="card-header">
        Шаблон OZON
      </div>
      <div class="card-body">
        <form method='post' enctype="multipart/form-data" id='form1'>
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="btn-group-vertical w-100"> 
          {% bootstrap_button button_type="submit" content="Отправить" %}
          </div>
        </form>
      </div>
    </div>
    <div style="display: flex; justify-content: center;"> 
      <a class="btn btn text-muted" href="{% url 'ozon:formatter' %}">Форматирование текста</a> 
    </div>
</div>
</div>

{% endblock %}

templates/ozon/ozon_list.html
{% extends "base.html" %} 
{% block title %} 
Лента  
{% endblock %} 
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-10">
    <div class="card mb-3 card text-white bg-dark mb-3">
      <div class="card-header text-white bg-dark mb-3 text-center">
        История шаблонов
      </div>

      {% for post in page_obj %}
      <div class="card text-white bg-dark mb-3" style="margin-bottom: 10px;">  
        <div class="card-header">
          <h5 class="card-title">Наименование: {{post.title}}</h5>
        </div>
        <div class="card-body">
          <p class="card-text">Штрих-код: {{post.barcode}}</p> 
          <p>
            <a class="btn btn-light btn-sm" href="{% url 'ozon:edit' post.id %}">Редактировать</a>
            <a class="btn btn-light btn-sm" href="{% url 'ozon:detail' post.id %}">Детали</a>
          </p>
        </div>
      </div>
      {% endfor %} 

    </div>
  </div>
</div>

{%include "includes/paginator.html" %}
{% endblock %}

templates/ozon/test_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Работа с шаблонами OZON
{% endblock %}

{% block content %}
<a class="btn btn text-muted" href="{% url 'ozon:list' %}">Список обработанных шаблонов</a> 
<a class="btn btn text-muted" href="{% url 'ozon:formatter' %}">Форматирование текста</a> 

<br><br>

<div class="row justify-content-center"> 
  <div class="col-md-8">
    <div class="card text-white bg-dark mb-3 text-center">
      <div class="card-header">
        Шаблон OZON
      </div>
      <div class="card-body">
        <form method='get' enctype="multipart/form-data" id='form1'>
          {% bootstrap_form search_form %}
          <div class="btn-group-vertical w-100"> 
          {% bootstrap_button button_type="submit" content="Искать" %}
          </div>
          {% if  select_categories  %}
            {% bootstrap_form select_categories %}
          <div class="btn-group-vertical w-100"> 
            {% bootstrap_button button_type="submit" content="Выбрать" %}
          </div>
        </form>
        {% endif %}
      </div>
    </div>
    <div style="display: flex; justify-content: center;"> 
      <a class="btn btn text-muted" href="{% url 'ozon:formatter' %}">Форматирование текста</a> 
    </div>
</div>
</div>

{% endblock %}