ozon/urls.py
from django.urls import path
from . import views

app_name = 'ozon'

urlpatterns = [
    path('', views.XlFormCreateView.as_view(), name='form'),
    path("<int:pk>/", views.XlFormDetailView.as_view(), name="detail"),
    path("edit/<int:pk>/", views.XlFormUpdateView.as_view(), name="edit"),
    path('list/', views.XlFormListView.as_view(), name='list'),
    path('edit_xl/<int:pk>/', views.edit_xl, name='edit_xl'),
    path('formatter/', views.Formatter.as_view(), name='formatter'),
    path('test/', views.FormView.as_view(), name='test')

]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),

]

sklad_tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('ozon/', include('ozon.urls')),
    path('purchaseorder/', include('purchaseorder.urls')),
    path("select2/", include("django_select2.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>ฅ^._.^ฅ</p>    
</footer>

templates/includes/head.html
{% load static %}
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">

templates/includes/header.html
{% load static %}

<header>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'pages:home' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Инструменты для склада
      </a>
      {% with request.resolver_match.view_name as view_name %}        
        <ul class="nav nav-pills">
          <li class="nav-item">              
            <a class="nav-link btn btn-light {% if view_name == 'pages:home' %} active {% endif %}" href="{% url 'pages:home' %}">
              Главная
            </a>
          </li>
          <li class="nav-item">              
            <a class="nav-link btn btn-light {% if view_name == 'ozon:form' %} active {% endif %}" href="{% url 'ozon:form' %}">
              Обработка шаблона
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link btn btn-light {% if view_name == 'purchaseorder:doc_list' %} active {% endif %}" href="{% url 'purchaseorder:doc_list' %}">
              Документы приемок
            </a>
          </li>
        </ul>
      {% endwith %}      
    </div>
  </nav> 
</header>

<style>
  .nav-link {
    background-color: dark; /* Черный цвет для неактивных */
    color: white;
  }
  .nav-link.active {
    background-color: white !important; /* Белый цвет для активных */
    color: black !important; /* Черный цвет текста для активных */
  }
  .nav-link:hover {
    color: gray; /* Серый цвет текста при наведении */
  }
</style>

templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav>
  <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <span aria-hidden="true">&laquo;</span>
             </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}